---
version: "3.6"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID={{ user_id }}
      - PGID={{ group_id }}
      - TZ=Europe/Madrid
      - SERVERURL={{ subdomain }}.{{ domain }}
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=auto 
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - /opt/docker-data/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
