- hosts: localhost
  vars:
    - user_id: 65534
    - group_id: 65534
  tasks:
    - name: build docker compose file
      template:
        src: docker-compose.yml
        dest: ../../docker-compose/prometheus/docker-compose.yml
