version: "3.6"
services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing
    restart: unless-stopped
    environment:
      - PUID={{ user_id }}
      - PGID={{ group_id }}
      - TZ=Europe/Madrid
    volumes:
      - /opt/docker-data/syncthing/config:/config
      - /opt/docker-data/photoprism/originals:/photoprism/originals
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
